### ISSUE TITLE
Error installing ratel

### ISSUE THREAD

**Issue by general-rishkin** [PMunch/ratel#18] opened 2024-12-22 13:03 UTC
I just did `nimble install ratel` and got the following errors during the install:

/home/gennadiy/.nimble/pkgs2/assume-0.7.2-2123f41ed45a26473a62bd522dc4fa851a824389/assume/spec.nim(162, 12) Warning: compiler bug workaround; see https://github.com/nim-lang/Nim/issues/18867 [User]
/home/gennadiy/.nimble/pkgs2/nimscripter-1.1.5-fcaab426f690a0b394249eaef07d9710af711404/nimscripter.nim(196, 23) `Error: expression 'callRoutine(intr_553649587, nsProc_553649588, [])' is of type 'PNode' and has to be used (or discarded); start of expression here: /tmp/nimble_249526/githubcom_PMunchratel/src/ratel.nim(22, 3)`.

My Nim version is 2.2.0.

**Comment by PMunch** [comment] 2024-12-22 20:07
This seems from the error message to be a bug in Nimscripter. Could you try raising the issue there? https://github.com/beef331/nimscripter/

**Comment by general-rishkin** [comment] 2024-12-23 11:18
Done!

On a side note, are you still working on/developing `ratel`?  It seems there has not been a commit for a while.

**Comment by PMunch** [comment] 2024-12-23 12:14
I definitely want to continue work on it, but I hit a bit of a wall when deciding how to create the higher level abstractions for e.g. SPI. So currently it's a bit on hold while I familiarise myself with more microcontrollers and buses.

**Comment by general-rishkin** [comment] 2024-12-23 12:31
That is great to hear!

I am just getting into programming the Arduino for Robotics and don't want to go the C++ route (I must admit I was tempted given the amount of libraries in C++).  Being able to use `ratel`  to upload to the board is ideal and allows me to do all other peripheral development in Nim.

**Comment by PMunch** [comment] 2024-12-23 18:10
I think we should keep this open. At least until the issue is resolved on the Nimscripter side: https://github.com/beef331/nimscripter/issues/30

**Comment by beef331** [comment] 2024-12-23 21:09
Should've been fixed on my side in `1.1.6`.

**Comment by PMunch** [comment] 2024-12-23 22:01
Great stuff!

**Closed as completed by PMunch** 2024-12-23 22:01 UTC
